MCU = STM32F401
BOARD = GENERIC_STM32_F401XC
BOOTLOADER = stm32-dfu

#WS2812_DRIVER = pwm
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
RGB_MATRIX_LED_COUNT = 61
QMK_CONSOLE = yes

#OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE
